
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: | 
              npm i
              npm run lint
      - run:
          command: |
            sudo apt update
            sudo apt install python3 python3-pip 
            sudo apt install awscli   
           
      - run:
          command: |
            pwd
            ls -tlahi
            find -type f -iname "config.yml"
            echo "[all]" > ~/project/ex1/inventory.txt
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> ~/project/ex1/inventory.txt
            cd ~/project/ex1
            ls -tlahi
            cat ~/project/ex1/inventory.txt
            

 # test:
 #   docker:
 #     - image: circleci/node:13.8.0
 #   steps:
 #     - checkout
 #     - run:
 #         command: |
 #           npm i
 #           npm run test



#mod for run
#  analyze:
#    docker:
#      - image: circleci/node:13.8.0
#    steps:
#      - checkout
#      - run: npm -v
#      - run: npm audit


workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - build
 #     - test:
 #         requires:
 #          - build
 #     - analyze:
 #         requires:
 #           - test

    