---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

-name: "install dependencies"
become: true
apt:
  name: "build-essential"
  state: latest
  update_cache: yes

-name: "install nodejs"
become: true
apt:
    name: "nodejs"
    state: latest
    update_cache: yes

-name: "install npm"
become: true
apt:
    name: "npm"
    state: latest
    update_cache: yes

-name: "install pm2"
become: true
apt:
    name: "pm2"
    state: latest
    update_cache: yes

-name: "install index.js file"
    copy:
      src: index.js
      dest: ~/web/index.js
      backup: yes

 - name: "execute commands"
    shell: |
      pm2 start ~/web/index.js -f